export enum AppRoute {
    WELCOME = '/welcome',
    LOGIN_VALIDATE_PHONE = '/login/validate-phone',
    REGISTER = "/register",
    REGISTER_PHONE = '/register/phone',
    REGISTER_VALIDATE_PHONE = '/register/validate-phone',
    REGISTER_EMAIL = '/register/email',
    REGISTER_FAMILY_MEMBERS = '/register/family-members',
    REGISTER_FAMILY_MEMBERS_ADD = '/register/family-members/add',
    REGISTER_REFERRAL_SHEET = '/register/referral',
    RECIPIENT_HOME = '/recipient-home',
    PROFILE = '/profile',
    REGISTER_REFERRAL_SHEET_SEND_DATE = '/register/referral/send-date',
    ENTITY_LOGIN = '/entity-login',
    ENTITY_LOGIN_PASSWORD_RECOVERY = '/entity-login/password-recovery',
}
